Vets-Who-Code/vets-who-code-app

package-lock.json, src/components/Footer.js, tests/components/__snapshots__/Footer.test.js.snap, yarn.lock
=> Add GitHub link

src/assets/css/heart-pulse.css, src/components/StickyButton.js
=> Add pulsing heartbeat to donate link

src/components/Layout.js, src/pages/about.js, src/pages/index.js, tests/pages/__snapshots__/about.test.js.snap
Moved jquery and bootstrap imports so they are availble to all children of the Layout component.
Closes #66
=> Fix issue when user visited a page directly removed Reference Error $ not defined

src/pages/mentor.js, tests/pages/__snapshots__/mentor.test.js.snap
Small tweak to mentor page
NA
Jerome asked for this change
Yes...Jest Snapshot
=> Update text on mentor page

src/components/Countdown.js
=> * [refactor] Update <Countdown /> component date.

package.json, src/assets/css/modal.css, src/components/DonateModal.js, src/components/Layout.js, tests/components/__snapshots__/DonateModal.test.js.snap, tests/pages/__snapshots__/donate.test.js.snap, yarn.lock
=> Add accessible modal component to app closes #73

src/pages/mentor.js
Fixed Typo on Mentor page from 'VetsWhocode' to 'VetsWhoCode'.
Typo mentioned in Slack channel
Grammer
Not needed.
=> Fixed 'VetsWhocode' typo on Mentor page.

gatsby-config.js, package.json, src/components/Layout.js, src/pages/index.js, tests/components/__snapshots__/layout.test.js.snap, tests/pages/__snapshots__/404.test.js.snap, tests/pages/__snapshots__/about.test.js.snap, tests/pages/__snapshots__/apply.test.js.snap, tests/pages/__snapshots__/contact.test.js.snap, tests/pages/__snapshots__/donate.test.js.snap, tests/pages/__snapshots__/index.test.js.snap, tests/pages/__snapshots__/mentor.test.js.snap, tests/pages/__snapshots__/syllabus.test.js.snap, tests/pages/index.test.js, yarn.lock
=> Add mailchimp and toast notifications

package.json, src/components/DonateModal.js, src/pages/donate.js, tests/pages/__snapshots__/donate.test.js.snap, tests/pages/__snapshots__/mentor.test.js.snap, tests/pages/donate.test.js, yarn.lock
Added iframe to donate page as a temporary fix for body scrolling.
**Skipped modal test for time being util it is reintroduced**
=> Update @reach/dialog for future use remove modal for time being closes #78.

gatsby-config.js, package.json, yarn.lock
Added Google Analytics plugin on fresh git branch
This feature was requested by @jeromehardaway
=> merged commits from google analytics

src/assets/css/custom.css, src/pages/syllabus.js
Updated the curriculum for JAMStack.
New curriculum.
Yes
- [X ] New feature (non-breaking change which adds functionality)
- [X ] I have read the **CONTRIBUTING** document.
- [ X] All new and existing tests passed.
=> Updated curriculum for JAMstack.

src/pages/apply.js, src/pages/contact.js, src/pages/mentor.js
Incorrect endpoints being used for the forms
When forms are being submitted on the website they are not being sent our slack channels for submitted forms.
=> Fix Form Submit Issues

package.json, src/components/FormValidator/FormValidator.js, src/components/FormValidator/index.js, src/pages/apply.js, tests/pages/__snapshots__/apply.test.js.snap, tests/pages/apply.test.js, tests/setup-test-env.js, yarn.lock
Updates the Application form to include new fields.
Adds form validator component
- modified: package-lock.json
- modified: package.json
- new file: src/components/FormValidator/FormValidator.js
- new file: src/components/FormValidator/index.js
- modified: src/pages/apply.js
- modified: tests/pages/__snapshots__/apply.test.js.snap
- modified: tests/pages/apply.test.js
- modified: yarn.lock
=> (feat) Update Application Form

src/components/Countdown/Countdown.js
Changed date to the next cohort start date.
=>  Changed Date

README.md
Updated the readme.MD to change the name of the file as well added the rebuilding the snapshot
=>  updated readME

src/components/Nav/Nav.js, src/components/Nav/nav.css, tests/components/__snapshots__/Layout.test.js.snap, tests/components/__snapshots__/Nav.test.js.snap, tests/pages/__snapshots__/404.test.js.snap, tests/pages/__snapshots__/about.test.js.snap, tests/pages/__snapshots__/apply.test.js.snap, tests/pages/__snapshots__/contact.test.js.snap, tests/pages/__snapshots__/donate.test.js.snap, tests/pages/__snapshots__/index.test.js.snap, tests/pages/__snapshots__/mentor.test.js.snap, tests/pages/__snapshots__/syllabus.test.js.snap
__ENHANCEMENT__ - *Add name next to logo*
\[[#95](https://github.com/Vets-Who-Code/vets-who-code-app/issues/95)\]
Adds name next to logo
- modified: src/components/Nav/Nav.js
- modified: src/components/Nav/nav.css
- modified: tests/components/__snapshots__/Nav.test.js.snap
- modified: tests/components/__snapshots__/layout.test.js.snap
- modified: tests/pages/__snapshots__/404.test.js.snap
- modified: tests/pages/__snapshots__/about.test.js.snap
- modified: tests/pages/__snapshots__/apply.test.js.snap
- modified: tests/pages/__snapshots__/contact.test.js.snap
- modified: tests/pages/__snapshots__/donate.test.js.snap
- modified: tests/pages/__snapshots__/index.test.js.snap
- modified: tests/pages/__snapshots__/mentor.test.js.snap
- modified: tests/pages/__snapshots__/syllabus.test.js.snap
=> (feat) Add name next to logo

gatsby-browser.js, src/components/Layout.js
Added a config to the gatsby-config file to load linked chat.
Linked chat was not working in prod.
closes #108
=> Add onClientEntry to gatsby-browser

gatsby-browser.js, src/assets/css/custom.css, src/components/Layout.js, src/pages/donate.js, tests/pages/__snapshots__/donate.test.js.snap, tests/pages/donate.test.js
Moved the testimonial below the donation form
Moved the donation form above the testimonial. Added media query to reduce the 800px size of the iframe parent container. Keeping it at 800px resulted in a large gap between the form and testimonial.
Fixes #110 
My assumption is it helps with conversion rates by reducing the time it takes the donor to get to the form. 
* Tested in FireFox and Chrome using various breakpoints.
* Ran Jest test suite
* Updated Snapshots
=> #110 Moved up donation form

src/components/Nav/Nav.js, src/components/Nav/nav.css, tests/components/__snapshots__/Layout.test.js.snap, tests/components/__snapshots__/Nav.test.js.snap, tests/pages/__snapshots__/404.test.js.snap, tests/pages/__snapshots__/about.test.js.snap, tests/pages/__snapshots__/apply.test.js.snap, tests/pages/__snapshots__/contact.test.js.snap, tests/pages/__snapshots__/donate.test.js.snap, tests/pages/__snapshots__/index.test.js.snap, tests/pages/__snapshots__/mentor.test.js.snap, tests/pages/__snapshots__/syllabus.test.js.snap
Added a new `className="donate"` to Nav.js
In nav.css :
```css
.donate:hover{
transition: .3s linear;
background-color: red;
}
```
https://github.com/Vets-Who-Code/vets-who-code-app/issues/116
We want to get as much attention to our fundraising efforts as possible. 
Updated test with `yarn test --updateSnapshot`
Tested in `yarn develop`
All tests passed
- [x ] New feature (non-breaking change which adds functionality)
- [x ] My code follows the code style of this project.
- [x ] I have read the **CONTRIBUTING** document.
- [x ] All new and existing tests passed.
=> Make the background of the donate button turn red on hover

src/pages/index.js
Patch sponsor slider from not showing
=> Path sponsor slider

.gitignore, package.json, src/components/Header/Header.js, yarn.lock
added typed js words
Added typed.js to the website as a package and implemented it above the fold.
An aesthetic enhancement to make the above the fold content more eye-catching.
Ran it on dev to see it work.
=>  added typed js words

src/components/Footer/Footer.js, tests/components/__snapshots__/Footer.test.js.snap, tests/components/__snapshots__/Layout.test.js.snap
Changed link to blog in site map
Link went to wrong blog.
Changed link and pressed it to ensure it was operational.
=> ChangeLinkInSiteMap, changed sitemap blog link

.github/workflows/nodejs.yml, README.md, gatsby-config.js, gatsby-node.js, package.json, scripts/develop.js, scripts/disable-blog-modules.js, scripts/enable-blog-modules.js, scripts/install.js, scripts/remove-git-hooks.js, src/components/Header/Header.js, src/templates/blog-helpers/index.js, src/templates/blog-post-template.js, src/templates/blog-template.js, yarn.lock
Add a method for developers to run app locally without needing API keys.
=> Add ability to run blog locally

.github/workflows/cleanup.yml
Remove extra dep install and Naming things is hard so I fixed it.
=> Im dumb and renamed the wrong thing. Remove extra yarn install

package.json, src/components/Forms/ApplyForm/ApplyForm.js, src/components/Forms/ContactForm/ContactForm.js, src/components/Forms/MentorForm/MentorForm.js, src/components/Forms/SubscribeForm/SubscribeForm.js, src/components/Forms/SubscribeForm/index.js, src/components/Forms/index.js, src/pages/apply.js, src/pages/contact.js, src/pages/index.js, src/pages/mentor.js, tests/components/Forms/ApplyForm.test.js, tests/components/Forms/ContactForm.test.js, tests/components/Forms/MentorForm.test.js, tests/components/Forms/SubscribeFrom.test.js, tests/components/__snapshots__/Footer.test.js.snap, tests/components/__snapshots__/Layout.test.js.snap, tests/components/__snapshots__/Nav.test.js.snap
Re-add MailChimp subscription signup form
=> Re-add subscribe form remove unnecessary props on forms

package.json, yarn.lock
=> Disable blog

gatsby-node.js, src/templates/blog-template.js
Move to fluid image for feature images on blog.
@gixxerblade please review, let me know if I missed anything.
https://5ebf5cc7cd1a370006d54ed6--vwc-site.netlify.app
Closes #149
=> Update blog images to be responsive

src/pages/contact.js
Remove the map from the Contact page
Closes #151.
=> Remove map from Contact page

src/assets/css/custom.css, src/pages/about.js
- Imported `'../assets/css/custom.css'` to `About` page
- Added CSS media query to custom.css to `text-align: justify;` on `<p>` and `text-align: center;` to `<h2>`.
- Updated testing snapshot. All tests passed.
Issue #148 
UI/UX display fix
- Using Jest
- On dev server viewing changes in Chrome
=> Fixed About page responsiveness for paragraphs and headers

src/assets/css/main.css
Add styles to bold, italicize, capitalize, and uppercase links on apply page 
JIRA Ticket PROD-2
To draw attention of users
Visually
[Netlify Preview](https://deploy-preview-165--vwc-site.netlify.app/)
=> Styled Links on Apply page to add emphasis. JIRA Ticket PROD-2

src/pages/donate.js
Delete introduction paragraph on donate age
JIRA ticket PROD-1
https://vets-who-code.atlassian.net/browse/PROD-1?atlOrigin=eyJpIjoiODEwZTBiN2YwYWM3NDU1Yjk2YTM0ZGMzNTg0OGNjMmQiLCJwIjoiaiJ9
Paragraph is redundant with donorbox iframe paragraph
Visually
None - will update with link when Netlify preview posts.
https://deploy-preview-167--vwc-site.netlify.app/
=> Remove paragraph from donation page

src/components/Forms/ApplyForm/ApplyForm.js
original: file
made by Jorge Garcia
almost done
Updated value of button in applyform.js 
NA
The button was lowercased
Tested locally
- [x ] I have read the **CONTRIBUTING** document.
=> Updated submit button text from "submit" to "Submit"

src/pages/mentor.js
Updates the title copy for the "your role" section to add missing words in the sentence.
#169 
Fixes a grammatical typo.
Existing tests pass.
N/a
=> Update mentor.js "your role" title value.

src/components/Footer/Footer.js, tests/components/__snapshots__/Footer.test.js.snap, tests/components/__snapshots__/Layout.test.js.snap
Closes
https://vets-who-code.atlassian.net/secure/RapidBoard.jspa?rapidView=1&projectKey=PROD&modal=detail&selectedIssue=PROD-15
https://vets-who-code.atlassian.net/secure/RapidBoard.jspa?rapidView=1&projectKey=PROD&modal=detail&selectedIssue=PROD-16
https://vets-who-code.atlassian.net/secure/RapidBoard.jspa?rapidView=1&projectKey=PROD&modal=detail&selectedIssue=PROD-17
=> Closes PROD-15 PROD-16 PROD-17

src/components/Countdown/Countdown.js
Added new date so it wouldn't be in the negative. March 1 2021.
=>  Added new date

src/pages/about.js
Add the ability for video to autoplay on mount.
https://vets-who-code.atlassian.net/secure/RapidBoard.jspa?rapidView=1&projectKey=PROD&modal=detail&selectedIssue=PROD-33
https://5f5ba0c87d3fa50007046899--vwc-site.netlify.app/about
=> Update video to play automatically

src/pages/about.js
Fixed background image on about page.
=> Change background-size from cover to auto

scripts/pre-start.js
Patch to fix running the app when no env file is present.
=> Patch for when env file not present

src/components/Forms/ApplyForm/ApplyForm.js, src/components/Forms/MentorForm/MentorForm.js
- Change the ApplyForm Submit button to all uppercase.
- Change the MentorForm Submit button to all uppercase.
Issue #163 
To match the rest of the application's style.
Visually and with automated Jest testing.
=> #163 Change submit buttons to uppercase.

gatsby-config.js, gatsby-node.js
=> Patch missed env variables

src/pages/donate.js
=> Patch bug with nav not being able to be closed on donate route

src/components/Nav/Nav.js
I changed the mobile nav menu behavior so that the menu closes when a navigation link is clicked. I did this by inserting a single line of code in the < ul > tag that served as the parent container for the navigation links: ```onClick={() => setIsNavOpen(false)}```
Before pushing these changes to the VWC repo, I did the following:
git checkout master
git pull
yarn
git checkout refactor/PROD-207
yarn
git merge master
yarn test --updateSnapshot
I inserted a single line of code in the < ul > tag that served as the parent container for the navigation links: ```onClick={() => setIsNavOpen(false)}```
[Issue #207](https://github.com/Vets-Who-Code/vets-who-code-app/issues/207)
I used Chrome dev tools to simulate a mobile environment (see Screenshots link below). I opened the navigation menu and …
=> Made Mobile Nav Bar Close on Select

src/components/Nav/Nav.js, src/components/SponsorSlider/SponsorSlider.js, tests/components/__snapshots__/SponsorSlider.test.js.snap
Closes #210, patched bug for closing nav on click outside, and fixed keys warning in sponsor slider.
Fixed issues with keys being on an incorrect node in the sponsor slider component as well.
=> Fix for nav staying open on click outside.

src/pages/donate.js
=> Add a title to the donorbox iframe

src/assets/css/main.css, src/components/Accordion/Panel.js, src/components/Footer/Footer.js, src/components/Forms/ApplyForm/ApplyForm.js, src/pages/syllabus.js, tests/components/__snapshots__/Footer.test.js.snap, tests/components/__snapshots__/Layout.test.js.snap
Changed <h_> heading to descending order(and changed CSS to match where needed).  Also changed Id labels to use "item".id instead of the map "index" number so each Aria-id is unique across all pages.
[Issue 221](https://github.com/Vets-Who-Code/vets-who-code-app/issues/221)
[Issue 220](https://github.com/Vets-Who-Code/vets-who-code-app/issues/220)
(https://github.com/Vets-Who-Code/vets-who-code-app/issues/223)
Used existing tests new tests not needed.
=> accessibility - edit heading levels and id labels

src/components/Accordion/Panel.js
Added aria labels to accordion plus and minus buttons
#226 
A11y issues
Lighthouse
=> added aria labels to accordion plus and minus buttons

src/assets/css/main.css, src/components/Forms/MentorForm/MentorForm.js, src/pages/mentor.js
- On the mentor page changed the `id={index}` to `id={guideline.id}` to ensure id's would be unique.
- Fixed headings issues by ensuring heading elements are in a sequentially-descending order
- Added `aria-labels` to all the form inputs.
Closes #222
Page not passing Lighthouse accessibility check with 100%.
Tested in Lighthouse.
=> Fixed accessibility issues with the Mentor page - closes #222

src/assets/css/main.css, src/components/Board/BoardCards.js, src/components/Board/boardCards.css, tests/components/BoardCards.test.js
Fixed assorted accessibility issues on Board and Blog pages
1. Changed low contrast text on Board page `<p>` to a higher contrast ratio
2. Changed heading elements so they are in sequentially-descending order on Board page
3. Added discernible names to Board members LinkedIn and Twitter links.
4. Changed low contrast text on Blog page to a higher contrast ratio
This PR will close #219 and #224 
Accessibility issues
Updated jest test snapshot
Ran new lighthouse tests
n/a
=> Fixed assorted accessibility issues on Board and Blog pages

src/components/Forms/ApplyForm/ApplyForm.js
=> changed headers back to accept

src/assets/css/main.css, src/components/Forms/ApplyForm/applyform.css
Changed the css variables of the `loader` class so it would match the background of the field where it is used.
Closes #237 
UI/UX 
Tested visually and Jest `yarn test`
=> Fixed the spinner so it would match the background in dark mode

src/assets/css/main.css
Removed the padding from `.main-navigation .navbar-nav li a span` (line 628 in main.css). 
Issue #233 
This solves the problem with the navbar cutting off on iPad.
This was tested on my local machine utilizing Chrome dev tools iPad feature.
=> Fix navbar on iPad 

src/templates/blog-template.js
Clean up based on comments @gixxerblade gave.
=> Remove log and clean up for bug on blog

gatsby-config.js, gatsby-node-helpers/index.js, src/components/Layout.js, src/components/SEO/index.js, src/pages/about.js, src/pages/apply.js, src/pages/contact.js, src/pages/donate.js, src/pages/mentor.js, src/pages/syllabus.js, src/pages/testimonials.js, src/templates/blog-post-template.js, src/templates/blog-template.js, tests/__mocks__/gatsby.js, tests/components/Forms/MentorForm.test.js, tests/components/SEO.test.js, tests/components/__snapshots__/Layout.test.js.snap
Add SEO component.
Needed to get SEO working.
Makes SEO work.
For SEO.
Jest and manual verification.
=> ➕ Add SEO component

gatsby-browser.js, gatsby-config.js, gatsby-ssr.js
Gonna use AWS to build chat app so we can control it more.
=>  removed chat component so that we can make our own

src/components/Header/Header.js, src/pages/index.js
Changed the text to reflect the evolved mission
=>  updated our language to reflect the direction we are moving towards

src/assets/css/main.css, src/components/Countdown/Countdown.js, src/pages/index.js, tests/components/Countdown.test.js
Reverts Vets-Who-Code/vets-who-code-app#264
=> Revert "Update countdown timer to functional component"

src/components/Countdown/Countdown.js, tests/components/Countdown.test.js
Updated Countdown.js component to a functional component
#263 
Modern react functional component is easier to read and use
Updated Countdown.test.js to pass this test.
=> Update countdown component

src/components/Accordion/Panel.js, src/pages/syllabus.js
Changed Syllabus page from Class component to functional component
#263 
Functional components are modern and easier to read
`yarn test` -> all test passed
=> Update syllabus to functional component 

package.json
=> Fix missed script in package.json

src/components/Footer/Footer.js, tests/components/__snapshots__/Footer.test.js.snap, tests/components/__snapshots__/Layout.test.js.snap
Changed number to the new one from Twilio
=> Add phone number

src/components/Footer/Footer.js, src/pages/about.js, src/pages/index.js, tests/components/__snapshots__/Footer.test.js.snap, tests/components/__snapshots__/Layout.test.js.snap
[#287: Add Podcast link to sitemap](https://github.com/Vets-Who-Code/vets-who-code-app/issues/287) 
Adding Podcast helps SEO
=> Add the podcasts page to the sitemap

src/components/Footer/Footer.js, src/components/SEO/index.js, src/pages/apply.js, src/pages/index.js, src/pages/jobs.js, src/pages/syllabus.js, src/templates/board-of-directors-template.js, tests/components/SEO.test.js
Make title dynamic based on the current page.
=> Add dynamic title for pages

package.json, yarn.lock
=> Add husky hooks and pretty quick

src/components/Forms/ApplyForm/ApplyForm.js
Bugfix Apply form remove call to undefined function
=> Remove call to undefined function

src/pages/index.js
=>  updated Date

README.md
=> Updated clone command from vwc-site to vets-who-code-app

package-lock.json, src/pages/index.js
Changed text from *"Launching something new Veteran's Day. Be sure to apply!"* to *"Sign Up For Our Next Cohort."*
[Update Text #332 ](https://github.com/Vets-Who-Code/vets-who-code-app/issues/332)
Veteran's Day has passed and it's a few months away. It's important to have relevant and up-to-date copy.
This has not been tested as I only updated the text and was unsure if it warranted a test. If I do need to perform a test, please let me know.
- [ x] My code follows the code style of this project.
- [x ] I have read the **CONTRIBUTING** document.
=> Updated text based on issue #332

src/assets/css/main.css, src/components/Header/Header.js, tests/components/__snapshots__/Header.test.js.snap
Changing the typed text to match closer to what we have on our Brand StyleGuide.
=>  added new language form our style guide to our web app

src/assets/css/main.css, src/pages/about.js, src/pages/index.js
Added about copy from style guide
=> J hardaway fix about page copy

src/pages/index.js
I updated the second paragraph on index.js with text provided by Jerome.
#362 
This provided a more in-depth description of the ideals and priorities of VWC.
Ran npm test, all tests passed. Looks like this page is not included in snapshot and is instead tested by Husky.
=> Updated 2nd paragraph text on Index.js

src/components/Header/Header.js, tests/components/__snapshots__/Header.test.js.snap
The text strings currently display as Times New Roman if you don't have Gotham installed locally on your machine.
Added inline styling to the Typed component in Header.js
=> Added Gotham font to Typed.js text

src/pages/_app.js
Added the favicon back for the website
Added a alink to the favicon in the document head
[376](https://github.com/Vets-Who-Code/vets-who-code-app/issues/376)
Provide a better experience for users
=> Add the HashFlag favicon

src/pages/_app.js
Add in a Graph and Twitter Card image for when the VWC-App is shared via social media.
#382 
At current, the image block was grayed out when someone would share the VWC-app on social media. This change will lead to a higher value of engagement when our link is shared.
I tested the tags at https://www.opengraph.xyz/url/https%3A%2F%2Fvetswhocode.io/ and input the photo to ensure it would populate.
=> Updated _app.js to include the new image for social media sharing

.github/workflows/WelcomeNewContributor.yml
Adding in new workflow to welcome 1st time contributors.
Creating an atmosphere where vets feel wanted and included when contributing to the application.
=> feat(Action): Added new action to welcome new contributors to the group

src/pages/code-of-conduct.js
Added whitespaces after H2's on code-of-conduct.js page. Same styling is used on about.js page as well so I used the same convention. 
For Centering Text "Our Pledge" on responsive layouts, I used the `success-story` CSS class on the div wrapper. This is consistent with the other divs on the same page as well.
[Issue](https://github.com/Vets-Who-Code/vets-who-code-app/issues/399)
This change will remove the congested headings and paragraphs on the Code of Conduct page. This change will also center the "Our Pledge" heading on mobile screens making it consistent with other headings on the page. 
All tests were passed.
=> Added spacing after H2's on Code of Conduct Page and aligned heading centrally on Responsive Layout

src/assets/css/custom.css, src/assets/css/main.css, src/pages/code-of-conduct.js
I fixed all the serif fonts to be sans-serif per the style guide
=> J hardaway fix fonts

.eslintrc.js, src/assets/css/resume-builder.css, src/pages/confirmation.js, src/pages/resume-builder.js, src/pages/resume-input.js
Added/started inputs for resume builder's contact page.
Inputs for contact page created using useState with onChange event. 
https://github.com/Vets-Who-Code/romeo-golf-cohort/issues/27
=> add contact inputs for resume builder

src/data/homepages/index.json
Initial updates to the existing copy on the index page. More changes are forthcoming to the text.
Changes are to the text part of the index page. Updating the copy to reflect better grammar, edits to avoid repetition in language, and general tightening of copy. 
Assigned to the task by Jerome. 
N/A - change only to text. No other updates should have been made that affect function of the site.
- [x ] Bug fix (non-breaking change which fixes an issue)
=> Update index.json text only

src/containers/hero/layout-04/index.tsx
Reverts Vets-Who-Code/vets-who-code-app#498
=> Revert "Hero h1 tag fix"

src/containers/donate-form/layout-01/index.tsx
=> Mobile Donation Form fix

src/data/blogs/combat-to-code.md
This Pull Request introduces a new blog post titled "From Combat to Code: Military Disciplines Translating Into Tech Success" to our site. It's aimed at sharing valuable insights on how military skills and disciplines can be effectively translated into success in the tech industry.
- **Content**: The blog discusses the valuable skills and experiences gained from military service that are applicable in tech careers, focusing on areas like discipline, communication, continuous learning, and adaptability.
- **Target Audience**: This post is tailored for veterans transitioning into tech careers, as well as our broader audience interested in understanding diverse career paths into technology.
- **Images**: An accompanying image that visually narrates the transition from military life to a …
=> Add Blog Post: "From Combat to Code: Military Disciplines Translating Into Tech Success"

src/components/menu/main-menu/index.tsx, src/data/menu.ts, src/data/sidebar-menu.ts, yarn.lock
I have managed to solve issue #537
=> added shop button on menu.ts file and changed tw-px to 15 px

package-lock.json, src/data/blogs/transferring-knowledge-between-careers.md
This pull request introduces a new blog post titled "Transferring Knowledge Between Careers" to the `src/data/blogs` directory. The blog post discusses the transfer of skills from non-tech to tech careers, emphasizing the importance of soft skills like process management, critical thinking, and teamwork. The author also shares personal experiences to illustrate the points.
* [`src/data/blogs/transferring-knowledge-between-careers.md`](diffhunk://#diff-f28bed2e63517fc3da7b193dc156fe1d44f9a4c0e4ba36856820e2ed64e5aebdR1-R40): Added a new blog post discussing the transfer of skills from non-tech to tech careers. The post highlights the importance of soft skills and shares personal experiences to illustrate the points.
=> Knowledge transfer blog

.idea/workspace.xml, src/data/blogs/ten-things-learned-after-10-years-at-vets-who-code.md
This pull request includes changes to two files: `.idea/workspace.xml` and `src/data/blogs/ten-things-learned-after-10-years-at-vets-who-code.md`. The changes in the `.idea/workspace.xml` file are mostly configuration settings for the IDE, while the changes in the `src/data/blogs/ten-things-learned-after-10-years-at-vets-who-code.md` file include the addition of a new blog post.
The most important changes include:
* [`.idea/workspace.xml`](diffhunk://#diff-9f043e4e89d784b579b6d75ea8704b232f9475fa5b3afd11f805fdf8e74c675cR1-R82): This file has been added, which includes configuration settings for the IDE such as component names and associated options. This change is important as it sets up the development environment settings for the project.
* …
=>  add new blog

src/data/blogs/using-ai-to-create-a-login-feature.md
This pull request includes the addition of a new blog post titled "Using AI to Create a Login Feature" in the `src/data/blogs/` directory. The blog post discusses how to use AI tools like GitHub Copilot Workspaces and OpenAI to efficiently create a login feature in a Next.js application. The post also includes a video walkthrough of the AI-driven development process.
Key Addition:
* [`src/data/blogs/using-ai-to-create-a-login-feature.md`](diffhunk://#diff-ca781a1e25f6e698ff94cf1cd318c4d4b152aa146464d1ecc4d4ed36940d2777R1-R44): Added a new blog post which discusses the use of AI tools for creating a login feature in a Next.js application. The post includes sections for an introduction, the creation of the login feature, a video walkthrough, and a conclusion.
=>  Add AI blog

src/data/blogs/cameron-porter-testimonial.md, src/data/blogs/my-journey-launching-jets-to-helping-businesses-take-off.md, src/data/blogs/testimonial-finding-vets-who-code.md, src/data/blogs/vets-who-code-servicing-tech-opportunities-to-those-who-served.md, src/data/blogs/vetswhocode-makes-be-better.md
This pull request includes changes to the `src/data/blogs` directory, adding several new blog posts. The posts cover various topics, including personal experiences of veterans transitioning from military life to tech careers, the impact of Vets Who Code on their journeys, and advice for other veterans considering similar career transitions.
New blog posts:
* [`src/data/blogs/cameron-porter-testimonial.md`](diffhunk://#diff-e7019892061270d742392761e77db50ece2c2388824d5ce6cc3129f55cd71cb8R1-R64): A testimonial from a former Coast Guard Yeoman about his transition into a tech career with the help of Vets Who Code.
* [`src/data/blogs/my-journey-launching-jets-to-helping-businesses-take-off.md`](diffhunk://#diff-2efd851aa04e7e9d0459c3de135ec541132a1163448a9aff70b84e667be98c5bR1-R48): A post …
=> Add dev testimonials

src/data/blogs/mastering-command-line-basics-using-project-board-tasks.md
This pull request includes a small but important change to the `src/data/blogs/mastering-command-line-basics-using-project-board-tasks.md` file. The change corrects a typo in the filename and adds a hyperlink to the Command Line Task Project Board for better accessibility.
Key changes:
* Renamed `src/data/blogs/mastering-command-line-basics-using-prject-board-tasks.md` to `src/data/blogs/mastering-command-line-basics-using-project-board-tasks.md` to fix a typo.
* Added a hyperlink to the Command Line Task Project Board in the blog content.
=>  fix url and add url

src/components/forms/apply-form.tsx
This pull request includes a small change to the `ApplyForm` component in the `src/components/forms/apply-form.tsx` file. The change adjusts the padding classes for the `div` and `h3` elements to improve the layout on different screen sizes.
* [`src/components/forms/apply-form.tsx`](diffhunk://#diff-c7a95841130757790ba4ef69590c3ba9b7045ce90bc6af44b340e1171345eaa8L53-R54): Modified the padding classes for the `div` and `h3` elements to enhance the layout on medium screens.
=>  Made apply form mobile friendly using tailwind

tailwind.config.js
Changed the color of a circle made by CSS.
=>  change color

src/containers/about/layout-02/index.tsx, src/containers/contact-info/layout-01/index.tsx, src/containers/course/layout-02/index.tsx, src/containers/cta/layout-02/index.tsx, src/containers/hero/layout-02/index.tsx, src/containers/newsletter/layout-01/index.tsx, src/containers/testimonial/layout-04/index.tsx
This pull request includes various updates to the layout components in the `src/containers` directory, focusing on code formatting improvements and image source updates. The most important changes involve reformatting component props for better readability and updating image sources to improve performance and consistency.
* [`src/containers/about/layout-02/index.tsx`](diffhunk://#diff-b217b2a6099f31e2fa014ba56089a99db07b8eb6a0c54078aaf4642b0b845718L17-R22): Reformatted the `AboutArea` component's props for better readability.
* [`src/containers/about/layout-02/index.tsx`](diffhunk://#diff-b217b2a6099f31e2fa014ba56089a99db07b8eb6a0c54078aaf4642b0b845718L30-L32): Reformatted the `SectionTitle` and `MottoText` components for better readability.
* …
=>  adding svgs in other places

package-lock.json, package.json
This pull request includes a change to the `package.json` file to update dependencies. The most important changes are:
Dependency updates:
* Added `@ai-sdk/azure` version `^1.0.7` to the dependencies.
* Updated the `ai` package from version `^2.2.8` to `^2.2.37`.
=>  added npm ai sdk

package-lock.json, package.json
This pull request includes updates to the `package.json` file to upgrade existing dependencies and add new ones. The most important changes include upgrading the `@playwright/test` dependency and adding several new TypeScript and testing-related dependencies.
Dependency updates:
* Upgraded `@playwright/test` from version `^1.37.1` to `^1.49.0`.
New dependencies:
* Added `@types/jest` with version `^29.5.14`.
* Added `jest` with version `^29.7.0`.
* Added `ts-jest` with version `^29.2.5`.
=>  added playwright and jest

src/containers/course/layout-05/index.tsx
This pull request includes a small change to the `src/containers/course/layout-05/index.tsx` file. The change updates the text of a button from "View All Modules" to "View All Subjects" to better reflect the content it links to.
* [`src/containers/course/layout-05/index.tsx`](diffhunk://#diff-b541928173295e12da6523f3dd96a1fbae940d2236ff5c2c115ef3aaac146a7cL56-R56): Updated button text to "View All Subjects" for better clarity.
=>  fixed text on button

blog-template.md, src/data/blogs/beyond-the-resume.md, src/data/blogs/reflections-on-the-military-influencer-conference-a-step-toward-inclusion-and-innovation.md
This pull request includes updates to blog content and metadata, as well as a fix for a markdown link syntax error. The most important changes include adding a new blog post with detailed metadata, correcting a link in an existing blog post, and updating the tags section in a blog template.
Content updates:
* [`src/data/blogs/reflections-on-the-military-influencer-conference-a-step-toward-inclusion-and-innovation.md`](diffhunk://#diff-bc1b58a545d30f559097fd3eed877de50760505f3a1abd9d62798051f49e0016R1-R40): Added a new blog post titled "Reflections on the Military Influencer Conference: A Step Toward Inclusion and Innovation" with comprehensive metadata and content.
Fixes:
* [`src/data/blogs/beyond-the-resume.md`](diffhunk://#diff-bac693d14ecd0f9992fee535f7a985cbd530a4e8ced3c12f64ee7196c9ae …
=>  added mic blog

src/components/vwc-grid/index.tsx, src/data/projects/vscode-extension-pack.json, src/data/projects/vscode-theme.json, src/data/projects/vwc-github-page.json, src/pages/projects.tsx
This pull request adds introductory text to the projects page and 3 additional projects.
- /src/pages/projects.tsx
- /src/data/projects
Resolves #675 #677 #678
=> Add additional projects & intro text

blog-template.md
Introduce a new blog template that includes a section for supporting Vets Who Code, encouraging donations and sponsorships to aid veterans in tech careers.
=> Add blog template

src/data/blogs/cameron-porter-testimonial.md
This pull request includes a change to the `src/data/blogs/cameron-porter-testimonial.md` file. The change updates the category and tags of a blog post.
Content updates:
* Changed the `category` from "Career Transition" to "Testimonial".
* Added "Testimonial" to the `tags` list.
=>  Update category and tags for Cameron Porter's testimonial blog post

src/data/blogs/introducing-the-vets-who-code-projects-page-design-and-implementation-journey.md
This pull request includes a small change to the `src/data/blogs/introducing-the-vets-who-code-projects-page-design-and-implementation-journey.md` file. The change adds a hyperlink to Jon Onulak's LinkedIn profile in the "About Me" section.
* [`src/data/blogs/introducing-the-vets-who-code-projects-page-design-and-implementation-journey.md`](diffhunk://#diff-6b3ead2769d56ff66b04038ae32e9241b38d15e55488a043ebcb0f1b59f95d07L23-R23): Added a hyperlink for Jon Onulak's LinkedIn profile in the "About Me" section.
=>  added linkedin profile of troop

src/components/menu/main-menu/megamenu.tsx, src/data/menu.ts
This pull request includes changes to the `megamenu` component and updates to the navigation items in the menu data. The changes focus on improving the styling and structure of the `megamenu` component and updating the navigation items to reflect new labels and paths.
Styling and structure improvements:
* [`src/components/menu/main-menu/megamenu.tsx`](diffhunk://#diff-c3adf9e831137f9327a7b8192586ce88f93be40eca739dcb0a211ecd9889bbc7L16-R16): Reordered the class names for better readability and consistency in multiple instances. [[1]](diffhunk://#diff-c3adf9e831137f9327a7b8192586ce88f93be40eca739dcb0a211ecd9889bbc7L16-R16) [[2]](diffhunk://#diff-c3adf9e831137f9327a7b8192586ce88f93be40eca739dcb0a211ecd9889bbc7L27-R27) [[3]](diffhunk://#diff-c3adf9e831137f9327a7b8192586ce88f93be40eca739dcb0a21 …
=>  refactor navigation menu labels and structure

src/data/blogs/tech-career-go-bag.md
This pull request includes a significant update to the `src/data/blogs/tech-career-go-bag.md` file. The change introduces a new audio feature that enhances the blog post by providing an audio breakdown of the Go Bag essentials.
Enhancements to the blog post:
* Added a styled `div` element containing an audio player for the Go Bag audio brief, including a link to open the audio in a new tab.
=>  add audio

src/data/blogs/how-to-beat-the-bots.md
This pull request adds a new blog post titled "How to Beat the Bots: A Veteran Developer's Guide to Navigating ATS in the Job Hunt." The blog provides actionable advice for veterans and developers on optimizing resumes to pass Applicant Tracking Systems (ATS). It includes strategies, tools, and a framework for tailoring resumes effectively.
* Added a new blog post file `how-to-beat-the-bots.md` under `src/data/blogs/`. The post includes a detailed guide on ATS optimization, featuring actionable tips, tools, and strategies specifically tailored for veterans transitioning into tech careers.
* Introduced a structured layout with sections such as "Key Takeaways," "What Is the ATS," "How We Train Our Troops," and "Tools of the Trade," among others. These sections provide clear, step-by-step …
=> Beat the bots audio

src/containers/hero/layout-04/index.tsx
This pull request refines the `HeroArea` component in `src/containers/hero/layout-04/index.tsx` by improving its structure, readability, and styling. The changes primarily involve reorganization of the JSX layout, adjustments to Tailwind CSS classes, and enhancements to the animated text section.
* Introduced a new wrapper `div` with `tw-flex tw-flex-col tw-items-center` to better organize the content and align it centrally.
* Reorganized the heading section by wrapping it in a `div` (`md:tw-mb-4`) and separating the animated text into its own flex container for better layout control.
* Updated Tailwind CSS class orders for consistency, such as swapping `tw-w-full tw-h-full` to `tw-h-full tw-w-full` for the hero image and tweaking padding classes for the hero area.
* Adjusted spacing and …
=>  Refactor HeroArea layout and improve heading structure

src/data/innerpages/become-a-mentor.json
This pull request updates the content of the `become-a-mentor.json` file to enhance messaging, improve clarity, and restructure the mentorship program details. The most significant changes include updating section titles and descriptions, modifying call-to-action buttons, and adding a detailed 8-step process for joining the mentorship program.
* Updated the `cta-area` section title and subtitle to emphasize joining the program and helping veterans, replacing the previous focus on donations.
* Revised the `gradation-area` section title to outline an 8-step process for joining the mentorship program, replacing the previous general description of mentorship opportunities.
* Changed the `cta-area` button path from `/donate` to `/about-us` and updated the button content from "Donate Now" to …
=>  making mentorship process more explicit

src/pages/blogs/[slug].tsx
This pull request includes updates to the `src/pages/blogs/[slug].tsx` file to adjust navigation paths and improve the layout structure for the blog page.
* Updated the navigation path and label for the blog section from `/blogs/blog-grid-sidebar` to `/blogs/blog` and changed the label from "blogs" to "blog" for consistency. ([src/pages/blogs/[slug].tsxL49-R56](diffhunk://#diff-07fa73f864faad0fbb6a8bd785cc56c67c0acd0397bdfd5acae38b10d95da2dcL49-R56))
* Reorganized the class names in the main container to improve readability and maintain consistent spacing across different screen sizes. ([src/pages/blogs/[slug].tsxL49-R56](diffhunk://#diff-07fa73f864faad0fbb6a8bd785cc56c67c0acd0397bdfd5acae38b10d95da2dcL49-R56))
=> Update blog breadcrumb path and adjust layout container styles

src/data/blogs/i-asked-the -google-deepmind-team-a-question.md
This pull request introduces a new blog post titled "I Asked the Google DeepMind Team a Question—Their Answer Says Everything About the Future of AI and Vets Who Code." The blog highlights insights from the Google DeepMind team at Google I/O 2025 and explores how AI advancements, particularly through Gemini, are reshaping career opportunities for veterans and military spouses in tech. The post also outlines how Vets Who Code is adapting its curriculum to prepare veterans for AI-augmented development.
* A new blog post file, `i-asked-the-google-deepmind-team-a-question.md`, was added, featuring:
- A detailed discussion of AI's role in empowering veterans and military spouses for careers in tech, based on insights from Google DeepMind leadership at Google I/O 2025.
- Embedded media, …
=> Google deepmind blog

.github/workflows/playwright.yml, src/data/menu.ts
This pull request updates the navigation menu structure in `src/data/menu.ts` to improve organization and user experience. The changes include restructuring menu items, adding new entries, and modifying existing ones.
* **Restructured Menu Items:**
- Consolidated the "About" section to include submenus like "About Page," "Subjects & Skills," and "FAQ."
- Moved "Apply" and "Mentor" to top-level menu items, with "Mentor" marked as a "hot" status item.
* **Added New Menu Entries:**
- Introduced a "Contact" menu item as a top-level entry.
- Added a "Game" submenu under the rebranded "Engage" section.
* **Modified Existing Entries:**
- Renamed "Lead" to "Engage" and updated its submenus to include "Blog" instead of "Stories" and retained "Shop" with external linking.
These changes aim to make …
=>  refactor: reorganize navigation structure and update labels

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/task.md
This pull request introduces standardized issue templates for bug reports, feature requests, and general tasks, along with configuration updates to improve issue tracking and community engagement. These changes aim to streamline the process of reporting issues and suggesting enhancements.
* [`.github/ISSUE_TEMPLATE/bug_report.md`](diffhunk://#diff-185833cb26d7ac66a4d39042fd576a820c2c2c6d05ad18973bb9c7dce77267c5R1-R28): Added a template for reporting bugs, including sections for description, reproduction steps, expected behavior, and context.
* [`.github/ISSUE_TEMPLATE/feature_request.md`](diffhunk://#diff-148870715557a13127284f8aeaa28002ed6b034268af13c5d030ab59fd078220R1-R22): Added a template for suggesting new features or enhancements, with fields for description, value, desired …
=> feat: add issue templates for bug reports, feature requests, and tasks

src/data/blogs/two-pointers-a-practical-technique-for-code-challenges.md
This pull request introduces a new blog post titled "Two Pointers: A Practical Technique for Code Challenges," aimed at helping developers master the Two Pointers technique for coding interviews. The blog includes detailed explanations, practical examples in Python and JavaScript, and insights into identifying and applying the technique effectively.
* **Overview of the Two Pointers Technique**: Explained the concept, patterns, and benefits of the technique, emphasizing its efficiency in terms of time complexity (O(n)) and space complexity (O(1).
* **Practical Examples**:
- **Palindrome Check**: Provided Python and JavaScript implementations to check if a string reads the same backward and forward.
- **Pair Sum Search**: Demonstrated how to find two numbers in a sorted array that sum to a …
=> feat: add blog post on the Two Pointers technique for coding interviews
