Vets-Who-Code/vets-who-code-app

- src/assets/css/main.css
- src/pages/index.js
- tests/pages/__snapshots__/index.test.js.snap
Used the hover pseudo class on .btn-subscribe to override the global hover state set by the bootstrap .btn:hover css class. The styles added were chosen in an effort to match other existing buttons located on the home page. 
Closes #62  
The change is required to improve the user experience, and maintain consistent styling throughout the site.
Ensured all tests passed. And manually checked several buttons for unexpected behaviors ensuring my changes did not affect buttons elsewhere.
The image below shows the subscribe button and apply button with the hover states toggled. I used the apply button styling as a template for the subscribe style.
> added styling to .btn-subscribe:hover fixing the undesired hover state set by global styles

- .gitignore
- src/assets/css/custom.css
- src/assets/css/main.css
Added underline to hover of site map links.
added online text decoration in main.css.
Accessibility
WCAG states that links need two indicators on hover for the user on links. We had only one.
I tested by hovering over site map link to see the underline.
>  AddUnderlineToSiteMapLinks, added styel to main.css

- src/components/Footer/Footer.js
- src/pages/about.js
- src/pages/apply.js
- src/pages/contact.js
- src/pages/donate.js
- src/pages/mentor.js
- src/pages/syllabus.js
- src/pages/testimonials.js
- tests/components/__snapshots__/Footer.test.js.snap
- tests/components/__snapshots__/Layout.test.js.snap
- Moved "Help Us Teach More Veterans How To Code" snippet found in all pages except for the home page to the footer component.
- Add ternary to query what location footer was at. If it was on the donate page `window.location.pathname !== "/donate"` it would not display "Help Us Teach More Veterans How To Code" and button. It displays on all other pages.
- Changed the donation button link in the footer from `<a href="/donate">` to `<Link to="/donate">` because Gatsby `<Link>` was designed to handle internal links.
- Found an error on About page where `<h2>` was a child of `<p>`. I moved the `<h2>` tag above the `<p>` tag. 
- Updated testing snapshot. All tests passed. 
Related to #150 
- Removes repeated code. Went from 84 lines to 14 lines
In Chrome, I checked the responsiveness in all …
> Move donate button to footer. Fixed donate button heading alignment

- src/components/Nav/Nav.js
- tests/components/__snapshots__/Layout.test.js.snap
- tests/components/__snapshots__/Nav.test.js.snap
Moved the donated link to the end of the nav
PROD-21: Place donate page at the end of Nav
Ran `yarn test --updateSnapshot` to ensure change was detected by jest
> PROD-21: Moved donate link to the end of the nav

- src/assets/css/custom.css
- src/pages/index.js
This PR addresses the Lighthouse accessibility issue of the heading elements not being in a sequentially-descending order on the homepage. Offending elements have been changed from `h4` to `h3` and styled as they were originally before the change. A class was created for the Next Cohort heading. An id was created for the Thank you for working with #VetsWhoCode heading in order to override a class.
This addresses issue #215 
This addresses accessibility standards. The fix brings the Lighthouse accessibility score to 100.
This was tested via Lighthouse.
> Fix heading a11y issue

- src/assets/css/main.css
- src/components/Nav/nav.css
- src/components/Toggle/toggle.css
This PR fixes the misalignment of the dark/light mode icon switcher in the navigation bar. It currently drops on a new line whenever the device's width is between 768 and 1024px. The reason is that it's absolutely positioned within these sizes. The fix is to remove the position absolute, and to make it cleaner, I've fine tuned the positioning for the smaller devices as well (i.e. between 320 and 767px).
This fixes #213.
Having the icon a new line for those widths, right underneath the main navigation makes it look out of place.
Different browsers and browser widths.
https://i.imgur.com/7C9U8NB.mp4
> Fix dark mode icon alignment across devices; fixes #213

- src/components/Toggle/toggle.css
Changed toggle position in mobile menu from 4.2rem to 1rem
#231 
Dark mode toggle position was off
Visually
> Changed toggle position in mobile menu

- src/pages/apply.js
- src/pages/mentor.js
- src/pages/syllabus.js
- Added a button to Apply page so that users could navigate to the prework page on Github more easily
- Added a small gutter to the paragraphs on the Apply, Syllabus, and Mentor pages to improve readability.
Closes #241 & #242 
- A button on the Apply page that directs visitors to the pre-work. It would be more clear at a glance that you can easily navigate to that documentation, especially helpful for people who skim the text.
- Keep the page consistent and improve readability on the site.
Tested through Chrome's Device Toolbar
> Added Apply page prework button and added margins to pages

- src/components/Footer/Footer.js
- tests/components/__snapshots__/Footer.test.js.snap
- tests/components/__snapshots__/Layout.test.js.snap
Changed the github footer url to link to https://github.com/sponsors/Vets-Who-Code in the Footer component. 
Closes #246 
Per Jerome
Visited link
Updated footer snapshot in jest
> Changed github footer url

- src/components/Footer/Footer.js
- tests/components/__snapshots__/Footer.test.js.snap
- tests/components/__snapshots__/Layout.test.js.snap
IRS finally consolidated all of our paperwork, changed the name from FRAGO to Vets Who Code, changed our charity status from a private foundation to a public charity and we have a new EIN, so changing the footer to reflect that.
>  adding public charity EIN

- src/components/Nav/Nav.js
- tests/components/__snapshots__/Layout.test.js.snap
- tests/components/__snapshots__/Nav.test.js.snap
Deleted out the span included within the Nav Donate link.
Issue #338  
This change enhances the lighthouse accessibility score by removing a span that did not meet the 4:1 color ratio compliance.
Executed the lighthouse report on localhost. Accessibility score is at 100. I did go back and double check the website and it too has the same score and does not flag the span anymore. Not sure if you'd still wish to merge this PR.
This update does affect the underline on hover transition for the Donate link.
> Updated Nav Donate Link

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/postCreate.sh
Adds support for .devcontainer / remote containers / codespaces
- Closes Issue #389 
.devcontainer support makes it easier for developers to iterate on changes to the codebase without having to configure their system with pre-reqs (nvm, npm, etc)
- Tested locally on macOS 12.4 Beta (21F5063e)
- Tested in Visual Studio Code Remote Containers
- Tested in Codespaces on forked repo
Signed-off-by: jldeen <jessicadeen@me.com>
> Add devcontainer support

- src/assets/css/main.css
Removed ' ' from sans-serif within main.css font-family section. This updated the font to show as expected.
#384 
Site font was transitioned to Gotham. Jerome noticed the footer still had some alibis.
Visually saw the change.
> fix(font): removed quotations from sans-serif which fixed footer font

- src/assets/css/nav.css
Set min width of Nav Bar to 821px so that once a window goes to 820px it switches to mobile version.
issue #400 
Nav bar changes to mobile version originally at 768px. The issue with this is that the nav bar is no longer inline with the each other. At 820px the Code of Conduct NAV bar option becomes two lines instead of one.
> set min-width of nav bar to 821px #400

- src/pages/api/api-helpers/index.js
- src/pages/api/contact.js
- tests/api/contact.test.js
Add a check for length in the footer form to help lessen the amount of spam received
Add a checkLength function to the api. The function checks for length of 1. If true, returns a 400
Tired of all the spam. Hoping this will lessen it
Wrote a unit test with a message with the length of 1
> Add a check for length in the footer form to help lessen the amount of spam received

- src/pages/donate.js
Remove Amazon smile as an option from the Donate page.
Removed Amazon smile div and re-sized remaining two divs to be 50/50. 
https://github.com/orgs/Vets-Who-Code/projects/46?pane=issue&itemId=28649331
Amazon Smile ended on 2/20/23 and this change is to reflect that it is no longer an option. 
- Verified removal of Amazon Smile section.
- Verified existing links on Donation page still work. 
- Tested responsiveness of remaining 2 options.
- Ran test suite to verify all tests still pass.
> refactor: remove amazon smile

- src/containers/hero/layout-04/index.tsx
Decided display block on span at smToMd screen sizes was more aesthetically pleaseing than simply adding a min-height to the over all element Resolves #496
> Hero h1 tag fix

- src/data/homepages/index.json
- src/data/innerpages/join-our-community.json
The VWC production app's "Learn More" button sends users to `start-here`. A path that is no longer valid. I went ahead and replaced it with `about-us` to match the footers "Start Here" link.
https://github.com/Vets-Who-Code/vets-who-code-app/issues/516
Important for the learn more to work since we want potential donors, mentors, veterans to be redirected appropriately to stay engaged. Returning a 404 could be the difference in getting that person into the community.
* On the VWC landing page, I clicked on "Learn More."
* Validated that I was redirected to `about-us`.
> Replaced start-here paths with about-us

- .vscode/settings.json
- src/components/widgets/two-col-list-widget.tsx
This PR addresses the issue of the broken 'About Us' link found in the website's footer. The link was not correctly redirecting to the 'About Us' page due to an incorrect URL path.
- Updated the href attribute in the footer's 'About Us' link to point to the correct URL.
- Verified that the updated link navigates to the 'About Us' page as expected.
1. Navigate to the website's homepage.
2. Scroll down to the footer section.
3. Click on the 'About Us' link.
4. Ensure that it successfully redirects to the 'About Us' page without any errors.
> fixed link in footer

- src/components/EmojiRain/index.tsx
- src/components/forms/apply-form.tsx
- src/components/forms/mentor-form.tsx
This pull request enhances the EmojiRain component by refining the positioning of emojis.
Changes:
- Utilized percentage-based positioning for improved responsiveness.
Reasoning:
- By switching to percentage-based positioning, the component adapts better to various viewport dimensions.
Notes:
- This pull request addresses the mentor form confirmation EmojiRain issue comparing to the Contact form EmojiRain.
- Feedback and suggestions for further enhancements are welcome.
> Mentor Form confirmation

- src/components/forms/apply-form.tsx
Description:
This pull request enhances the EmojiRain component by refining the positioning of emojis.
Changes:
- Added EmojiRain component to the apply-form component.
- Utilized percentage-based positioning for improved responsiveness.
Reasoning:
- By switching to percentage-based positioning, the component adapts better to various viewport dimensions.
Impact:
- Enhances the visual appearance of the EmojiRain component on the apply-form component.
Additional Notes:
- This pull request addresses the apply-form-confirmation issue.
- Feedback and suggestions for further enhancements are welcome.
> apply form confirmation

- src/layouts/footers/footer-01.tsx
Problem:
The website currently does not show the nonprofit EIN on the website
Solution:
At the footer, place the following statement about the copyright info, perhaps centered to the website or near the Candid image. It just needs to look good at all sizes!
Vets Who Code is a registered 501(c)(3) nonprofit under EIN 86-2122804. Donations are tax-deductible to the fullest extent allowable under the law.
I placed the statement by borrowing a className and modifying the margin-top of the <p> tag:  
This is how it looks on the website:
> Add EIN to the website footer #542

- src/containers/course-details/index.tsx
- src/layouts/footers/footer-01.tsx
- src/pages/curriculum/[slug].tsx
Problem:  
When you click on the pages available from the Modules page: https://vetswhocode.io/curriculum/subjectsthe header looks different from what's on all the other pages. (See homepage for the right example)
The header needs to remain the same across all pages of this webapp.
Solution:
On src/pages/curriculum/[slug].tsx, I saw an inconsistency on line number 3: import Layout01 from "@layout/layout-02";
I changed it to import Layout01 from "@layout/layout-01";
Now, we can see the same header across all pages on Modules.
Before:
After:
> #554 Header looks different on inner pages; needs to be same

- src/containers/hero/layout-04/index.tsx
This PR introduces an overlay with `rgba(9, 31, 64, 0.5)` background color on top of the hero area's background image. The goal of this change is to dim the background image slightly, enhancing the readability of text and the visibility of other elements in the hero area. 
**Changes Made:**
- Added a `<div>` with inline styles for `backgroundColor: rgba(9, 31, 64, 0.5)` and absolute positioning. This div serves as an overlay on the hero background image, ensuring that the image is dimmed without affecting the opacity of the content on top.
- Ensured that the overlay covers the entire area of the background image by setting its position to absolute and extending it to all corners of the container.
**Rationale:**
The background image of the hero area, while visually appealing, can sometimes …
> Add Opacity Overlay to Hero Background Image for Improved Readability

- src/data/blogs/post-bootcamp-tips-for-rookies.md
- src/data/blogs/prompt-engineering-for-javascript-engineers.md
This pull request introduces changes to two blog posts in the `src/data/blogs` directory. The first change includes the addition of a `postedAt` field to the `post-bootcamp-tips-for-rookies.md` file. The second change is more extensive, adding a new blog post titled "Elevating JavaScript Development: Mastering Prompt Engineering with ChatGPT" to the `prompt-engineering-for-javascript-engineers.md` file. This new blog post includes metadata, an introduction, several sections discussing prompt engineering, and a conclusion.
* [`src/data/blogs/post-bootcamp-tips-for-rookies.md`](diffhunk://#diff-b4360e71db44c1058760fe88f0e54418505138d7a45ed5225429ed596b4d2707R3): Added a `postedAt` field to provide a timestamp for when the blog post was published.
* …
> Elevating JavaScript Development: Mastering Prompt Engineering with ChatGPT

- src/data/blogs/celebrating-progress-on-veterans-day-2023.md
- src/data/blogs/combat-to-code.md
- src/data/blogs/how-veterans-use-ai-at-vets-who-code.md
- src/data/blogs/introducing-the-new-and-improved-vets-who-code-app.md
- src/data/blogs/post-bootcamp-tips-for-rookies.md
- src/data/blogs/prompt-engineering-for-javascript-engineers.md
- src/data/blogs/why-devsecops-is-a-perfect-match-for-veterans.md
- src/data/blogs/why-i-created-a-portfolio-checklist-for-javaScript-engineers.md
This pull request primarily involves changes to the blog posts in the `src/data/blogs` directory. The changes include image URL modifications, addition of a new blog post, and alterations to the content of an existing blog post. The image URL modifications involve adding `g_auto` to the Cloudinary URLs, which enables automatic gravity selection for better cropping. The new blog post added is titled "Harnessing AI to Transform Coding Education for Veterans". Lastly, the content of the blog post "Elevating JavaScript Development: Mastering Prompt Engineering with Chat" has been significantly revised.
Image URL modifications:
* [`src/data/blogs/celebrating-progress-on-veterans-day-2023.md`](diffhunk://#diff-d440cd87c15ca35ebf82567465c63e1add2d76f46155e11ba62e5b4a96b71d81L8-R8): Updated the …
> Add ai engineering blog

- src/data/blogs/system-requirements-and-architecture-patterns-for-javascript-engineers.md
This pull request includes a new blog post titled "Leveraging Prompt Engineering in Software Development: System Requirements & Architecture Patterns with JavaScript, TypeScript, Next.js, Vue, and Angular". The blog post discusses the concept of prompt engineering in software development, with a focus on design techniques, patterns, and strategies. It discusses in detail eight different patterns: Requirements Simulator Pattern, Specification Disambiguation Pattern, API Generator Pattern, API Simulator Pattern, Few-shot Code Example Generation Pattern, Domain-Specific Language (DSL) Creation Pattern, Architectural Possibilities Pattern, and Change Request Simulation Pattern. Each pattern is explained with examples across different technologies including JavaScript, TypeScript, Next.js, …
> System requirements and architecture patterns

- .devcontainer/devcontainer.json
- yarn.lock
This pull request includes a modification to the `.devcontainer/devcontainer.json` file to enhance the development environment. The changes include an update to the Visual Studio Code settings and extensions to improve code formatting and linting.
Key changes:
* [`.devcontainer/devcontainer.json`](diffhunk://#diff-24ad71c8613ddcf6fd23818cb3bb477a1fb6d83af4550b0bad43099813088686L12-R45): Added `editor.formatOnSave` setting to automatically format code on save. Also, ESLint validation has been enabled for JavaScript, TypeScript, and their React variants. Code actions on save have been set to fix all ESLint issues automatically. The extensions list has been updated to include Prettier for code formatting and a Tailwind CSS IntelliSense extension for better CSS class name completion and error …
> Add ESLint and Prettier configurations to devcontainer.json

- .github/workflows/playwright.yml
This pull request includes improvements to the GitHub Actions workflow for Playwright tests. The changes primarily focus on adding caching for node modules and Playwright browsers to speed up the test runs. 
Here is a summary of the key changes:
* [`.github/workflows/playwright.yml`](diffhunk://#diff-7afcd2d8f7b49bda74843f209eefb7b2da45f7e7803bf2e4bd636699b76aa2d3R2-R53): Added caching for node modules using `actions/cache@v2`. This caches the `node_modules` directory based on the hash of the `yarn.lock` file, which will speed up the installation of dependencies in future runs if the `yarn.lock` file hasn't changed.
* [`.github/workflows/playwright.yml`](diffhunk://#diff-7afcd2d8f7b49bda74843f209eefb7b2da45f7e7803bf2e4bd636699b76aa2d3R2-R53): Added caching for Playwright browsers. This …
> updated playwright.yml

- src/data/blogs/beyond-the-resume.md
This pull request includes a significant addition to the `src/data/blogs/beyond-the-resume.md` file. A new blog post titled "Beyond the Resume: A Veteran's Value Revealed at Methodist" has been added. The post discusses the value of hiring veterans in the tech industry, focusing on a success story of a veteran named Adrian Grimm at Methodist Le Bonheur Healthcare. The post also encourages other companies to consider hiring veterans.
Key Additions:
* [`src/data/blogs/beyond-the-resume.md`](diffhunk://#diff-bac693d14ecd0f9992fee535f7a985cbd530a4e8ced3c12f64ee7196c9aeef00R1-R55): Added a new blog post titled "Beyond the Resume: A Veteran's Value Revealed at Methodist". The post includes sections such as an introduction, recognizing veteran potential, Adrian's impact at Methodist, technical …
>  add hot new article

- src/pages/blogs/blog/index.tsx
- src/pages/blogs/blog/page/[page].tsx
This pull request includes changes to the `BlogGrid` component in the `src/pages/blogs/blog/index.tsx` and `src/pages/blogs/blog/page/[page].tsx` files. The change modifies the `currentPage` prop in the `Breadcrumb` component, updating the string from "Blog" to "Hashflag Blog" and "Blog Grid" to "Hashflag Blog" respectively.
Changes:
* [`src/pages/blogs/blog/index.tsx`](diffhunk://#diff-cee74069e6c8440d03bd77493f83304d9d263bcdcc8ec687d9f4749e8a581f0eL31-R31): Updated the `currentPage` prop in the `Breadcrumb` component from "Blog" to "Hashflag Blog".
* `src/pages/blogs/blog/page/[page].tsx`: Updated the `currentPage` prop in the `Breadcrumb` component from "Blog Grid" to "Hashflag Blog". ([src/pages/blogs/blog/page/[page].tsxL32-R32](diffhunk://#diff-9c58097a9254bc3f00ea2212aeef542d2180c53 …
>  add name change

- blog-template.md
- src/data/blogs/bridging-the-gap-josh-morton-testimonial.md
- src/data/blogs/hiring-wrong-in-the-era-of-ai.md
This pull request includes changes to three different blog posts. The most important changes include removing the template content from `blog-template.md`, adding a new blog post titled "Bridging the Gap: From Combat Boots to Code – A Journey with Vets Who Code", and making a minor edit to the `hiring-wrong-in-the-era-of-ai.md` blog post.
Blog content removal:
* [`blog-template.md`](diffhunk://#diff-eb1b47ab8548e766a7eee494c6176272357699b7e52c66e03cd03a34b5c1d781L17-L35): Removed template content from the file, which included the introduction, section headers, subsections, and conclusion.
New blog post:
* [`src/data/blogs/bridging-the-gap-josh-morton-testimonial.md`](diffhunk://#diff-ab07f487046d5a81212812518a58834142151b5af3d9cfbd7c01909212fbf437R1-R61): Added a new blog post titled …
>  added Josh Morton testimonial

- src/pages/login.tsx
- src/pages/profile.tsx
- yarn.lock
This pull request includes changes to the `Profile` component in `src/pages/profile.tsx` to streamline the user redirection process upon logout and when the user is not logged in.
Changes to user redirection:
* [`src/pages/profile.tsx`](diffhunk://#diff-27493a45525c74e39bd9dad7aa2a186f2a21f507c892506369450d3d965f42c2L23-R23): Modified the redirection URL from `/login-register` to `/login` in the `useEffect` hook to ensure users are directed to the login page if they are not logged in.
* [`src/pages/profile.tsx`](diffhunk://#diff-27493a45525c74e39bd9dad7aa2a186f2a21f507c892506369450d3d965f42c2L39-R39): Updated the `handleLogout` function to redirect users to the `/login` page instead of `/login-register` after logging out.
>  fixed url for login upon log out

- src/data/blogs/mastering-command-line-basics-using-prject-board-tasks.md
This pull request adds a new blog post to the `src/data/blogs` directory, highlighting the importance of command line skills and introducing a new resource from Vets Who Code. The most important changes include the addition of metadata, a detailed article, and a YouTube video embed.
* [`src/data/blogs/mastering-command-line-basics-using-prject-board-tasks.md`](diffhunk://#diff-4bd5226121d16d9518a3e379b1d78098ea4f0385c79c53254ad3ad6fd68fdd8eR1-R55): Added a new blog post titled "Mastering the Command Line: A Fundamental Skill with Vets Who Code" by Jerome Hardaway. This post emphasizes the significance of command line skills, introduces the Command Line Task Project Board, and provides steps on how to use it. It also includes a call to support Vets Who Code through donations or …
>  added new blog

- src/data/site-config.ts
This pull request includes a small but important change to the `src/data/site-config.ts` file. The change updates the `url` property to reflect the correct website URL for Vets Who Code.
* [`src/data/site-config.ts`](diffhunk://#diff-a189ae4d1657207fdc4f87e5f7711375f6b9964def6f8e1a8e4b1cb8265d334aL6-R6): Updated the `url` property from `"https://yourwebsite.com"` to `"https://vetswhocode.io"`.
>  add url to site conifg

- src/components/forms/apply-form.tsx
- src/components/forms/mentor-form.tsx
- src/utils/formValidations.ts
- Added validation to the "GitHub Portfolio or LinkedIn" field in the "mentor-form"
- Added validation to the "LinkedIn Account Name" filed in the "apply-form"
- Added validation to the "GitHub Account Name" filed in the "apply-form"
Related to issue: https://github.com/Vets-Who-Code/vets-who-code-app/issues/593
> Add form validations

- src/components/forms/contact-form.tsx
- src/containers/contact-form/layout-02/index.tsx
Enhance the contact form's user experience by refining the layout, improving styling, and ensuring better feedback on submission.
> Improve contact form design and functionality

- src/layouts/headers/header.tsx
This pull request includes a small change to the `src/layouts/headers/header.tsx` file. The change updates the text and the target date for the countdown timer in the header component.
* Updated the header text from "Our 10th Anniversary Is In" to "Our Next Cohort".
* Changed the `CountdownTimer` target date from "2024/05/15" to "2025/03/13".
>  update the cohort timer

- src/pages/api/auth/[...nextauth].ts
- src/pages/api/auth/error.tsx
- src/pages/login.tsx
This pull request includes several changes to improve the authentication flow and error handling in the application. The most important changes include adding a utility function for handling GitHub API requests with a timeout, enhancing error handling and logging, and creating a custom error page for authentication errors.
Improvements to GitHub API requests and error handling:
* `src/pages/api/auth/[...nextauth].ts`: Added a utility function `fetchWithTimeout` to handle GitHub API requests with a timeout and integrated it into the `signIn` callback to manage rate limiting and error scenarios. ([src/pages/api/auth/[...nextauth].tsR5-R26](diffhunk://#diff-7475ff53d7b230ebd130cb30b4cc074cc8845ceeebf67518f1f4717968a34f10R5-R26), [src/pages/api/auth/[...nextauth].tsL19-R132](diffhunk://#diff-7 …
>  add login updates

- src/pages/login.tsx
- src/pages/profile.tsx
This pull request includes updates to the login and profile pages to improve session handling and user experience. The most important changes involve updating the session management logic, improving error handling, and enhancing the user interface during loading states.
* [`src/pages/login.tsx`](diffhunk://#diff-cd54149b4c3f0a12502acd6d824b642db9085fd7c1a403bd829ce37439294a2eL23-R50): Added session data to the `useSession` hook and updated the `useEffect` hook to handle authenticated states more effectively by using `router.replace` instead of `router.push`. Improved error handling during redirection.
* [`src/pages/profile.tsx`](diffhunk://#diff-27493a45525c74e39bd9dad7aa2a186f2a21f507c892506369450d3d965f42c2L9-R59): Replaced the custom user context with the `useSession` hook from …
>  add updated code

- src/components/forms/apply-form.tsx
- src/pages/api/apply.ts
This pull request adds a field to the student application form to indicated if the applicant has completed any prior bootcamps or programs.
- Adds a checkbox for the applicant to indicate if any prior programs have been completed
- If checked, a text area will show where programs may be listed. If the checkbox is checked, entering text into the text box is required. The text area will animate into view as the check box is checked.
- All fields below the text area will animate up or down as the check box is checked or unchecked.
- Relevant fields added to `/api/apply` endpoint and the corresponding slack channel output
- /src/components/forms/apply-form.tsx
- /src/pages/api/apply.ts
Resolves #595
> Add application question for prior bootcamps or programs

- src/components/socials/social-01.tsx
- src/components/widgets/text-widget.tsx
This pull request includes changes to add a YouTube social link to two components in the codebase. The most important changes are as follows:
Enhancements to social links:
* [`src/components/socials/social-01.tsx`](diffhunk://#diff-315482d1901b9fb0da16f827ddb580415a462a68a2d1e9ab3b4bd99e23bd59baR26-R32): Added a YouTube social link with the label "youtube" and the class "tw-px-2.5".
* [`src/components/widgets/text-widget.tsx`](diffhunk://#diff-3c657162d8684b6ca181afa80dd4df2d05e76f7b6add3523ce5f35266e1c585aR44-R46): Added a YouTube social link with the label "youtube".
>  Add YouTube link to Social and Text widgets

- src/pages/blogs/blog/index.tsx
- src/pages/blogs/blog/page/[page].tsx
This pull request includes changes to the breadcrumb text in the blog pages to update the current page label from "Hashflag Blog" to "Vets Who Code Blog".
Changes to breadcrumb text:
* [`src/pages/blogs/blog/index.tsx`](diffhunk://#diff-cee74069e6c8440d03bd77493f83304d9d263bcdcc8ec687d9f4749e8a581f0eL27-R27): Updated the `currentPage` label in the `Breadcrumb` component to "Vets Who Code Blog".
* `src/pages/blogs/blog/page/[page].tsx`: Updated the `currentPage` label in the `Breadcrumb` component to "Vets Who Code Blog". ([src/pages/blogs/blog/page/[page].tsxL28-R28](diffhunk://#diff-9c58097a9254bc3f00ea2212aeef542d2180c5332f655b5d154de9fe3da03a38L28-R28))
>  Update breadcrumb current page label to Vets Who Code Blog

- src/data/homepages/index.json
This pull request includes a small update to the `src/data/homepages/index.json` file, replacing the source URL of an image with a new one.
* [`src/data/homepages/index.json`](diffhunk://#diff-4e2e270fa5735804889bde55c23721dc839113a9eeee178b0c09c1a03787dd0aL48-R48): Updated the `src` field of the image with `id: 1` to use a new Cloudinary URL for the image.
> Update hero-area image source

- src/data/innerpages/become-a-mentor.json
This pull request includes a minor change to the `src/data/innerpages/become-a-mentor.json` file. The change removes an unnecessary trailing comma from the JSON object, ensuring proper formatting.
> Update button content in the CTA area of the mentorship page

- src/layouts/headers/header.tsx
This pull request updates the header component to reflect new event details and adjust the countdown timer accordingly.
Content updates in the header:
* Updated the header text from "Our Next Cohort" to "Platform Launch + Vets Who Code Demo Day" to reflect the new event. (`src/layouts/headers/header.tsx`, [src/layouts/headers/header.tsxL38-R42](diffhunk://#diff-401ed5a5190ad062af3f1fe2918d8224799dc545971905a71ca5fad4ded0bb87L38-R42))
* Changed the `CountdownTimer` target date from "2025/03/03" to "2025/11/11" to align with the updated event schedule. (`src/layouts/headers/header.tsx`, [src/layouts/headers/header.tsxL38-R42](diffhunk://#diff-401ed5a5190ad062af3f1fe2918d8224799dc545971905a71ca5fad4ded0bb87L38-R42))
>  add vets who code platform launch date

- src/data/innerpages/about-us.json
- src/data/innerpages/theory-of-change.json
- src/pages/about-us.tsx
- src/pages/theory-of-change.tsx
This pull request introduces significant updates to the "About Us" page and adds a new "Theory of Change" page to the project. The changes enhance content structure, improve user engagement, and extend functionality. Below is a breakdown of the most important updates grouped by theme:
* Refactored the "About Us" page's call-to-action (CTA) content to simplify and focus messaging, replacing a lengthy description with concise and impactful text.
* Added a new JSON data file (`theory-of-change.json`) to define the content structure for the "Theory of Change" page, including sections for core beliefs, inputs, activities, outputs, outcomes, and long-term impact.
* Introduced a new `TheoryOfChange` page (`theory-of-change.tsx`) that dynamically renders content based on the new JSON data file, …
>  feat: add Theory of Change page and enhance About Us with a link to it

- src/layouts/footers/footer-01.tsx
This pull request updates the footer component in the `src/layouts/footers/footer-01.tsx` file to replace the displayed image and link with updated information. 
* Updated the link to point to the Candid profile page for "Vets Who Code" (`https://app.candid.org/profile/9981881/vets-who-code-86-2122804`) and added `target="_blank"` and `rel="noreferrer"` attributes to ensure the link opens in a new tab securely.
* Replaced the image source with a new URL (`https://widgets.guidestar.org/prod/v1/pdp/transparency-seal/9981881/svg`) and updated the `alt` text to "Candid/Guidestar Transparency Seal" while adding a `title` attribute for better accessibility and context.
>  fix: update Candid seal image and link to transparency seal

- .tailwind-debug.css
- package-lock.json
- package.json
- src/assets/css/engagement-modal.css
- src/components/EngagementModal.module.css
- src/components/EngagementModal.tsx
- src/components/EngagementModal.tsx.fixed
- src/components/ui/section/index.tsx
- src/containers/newsletter/layout-02/index.tsx
- src/pages/index.tsx
- tailwind.config.js
- yarn.lock
This pull request introduces a new `EngagementModal` component, enhancements to animations and accessibility, and minor updates to existing components and dependencies. The changes focus on improving user interaction and modularity across the codebase.
* **Engagement Modal Implementation**: Added a new `EngagementModal` component with animations, accessibility features (e.g., focus trap and ESC key handling), and session-based display logic. It includes customizable headline, body, and call-to-action buttons. [[1]](diffhunk://#diff-6953988903c2c8ccdac678a1e5641963b1f4d00c74aa44153ce09665bfa26ea8R1-R211) [[2]](diffhunk://#diff-a0479b509155d4bef93e1457f9359ed3470d74d63f6e98325a38534767b3d6a9R1-R209)
* **Animation Enhancements**: Introduced custom "wiggle" animations for emojis in …
>  Add Engagement Modal with custom animations and accessibility features

- src/data/blogs/using-ai-to-create-a-login-feature.md
This pull request makes a small update to the `src/data/blogs/using-ai-to-create-a-login-feature.md` file. The change optimizes the image source URL by adding automatic format, quality, and resolution adjustments to improve loading performance.
>  fixed url for performance

- package-lock.json
- package.json
- src/assets/css/font-awesome-pro.min.css
- src/data/programs/core-curriculum.mdx
- src/data/programs/mentorship.mdx
- src/data/programs/mission-ready.mdx
- src/data/programs/studio.mdx
- src/pages/programs.tsx
- src/pages/programs/[slug].tsx
- src/pages/programs/core-curriculum.mdx
- src/pages/programs/index.mdx
- src/pages/programs/mentorship.mdx
- src/pages/programs/mission-ready.mdx
- src/pages/programs/studio.mdx
- yarn.lock
This pull request introduces significant enhancements to the `Programs` section of the application, including new program pages, updates to dependencies, and improvements to styling. The changes focus on creating a structured and user-friendly experience for veterans exploring program offerings.
* **Dynamic Program Listing**: Added a new `src/pages/programs.tsx` file to dynamically list all programs with their descriptions and links to individual pages. This includes fetching program metadata using `getStaticProps`.
* **Individual Program Pages**: Created dynamic pages for each program (`src/pages/programs/[slug].tsx`) to display detailed information. These pages use MDX for content rendering and `getStaticPaths` for dynamic routing. …
> Program pages
